sudo: required

services:
  - docker

before_install:
- docker build -t joramk/fc28-haproxy:latest .
- docker run --tmpfs /run --tmpfs /tmp -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name fc28_haproxy -d joramk/fc28-haproxy:latest

script:
- while sleep 5; do docker top fc28_haproxy ; docker logs fc28_haproxy ; docker ps -a | grep ago ; if [ `docker ps -a | grep '(unhealthy)' | wc -l` != "0" ]; then exit 1; fi ; if [ `docker ps -a | grep '(healthy)' | wc -l` != "0" ]; then exit 0; fi ; if [ `docker ps -a | grep 'starting)' | wc -l` == "0" ]; then exit 1; fi ; done
